[package]
name = "owe-waywallen-scene-renderer"
version.workspace = true

[[bin]]
name = "waywallen-wescene-renderer"
module = "waywallen.scene_entry"
sources = [
  "scene_entry.cppm",
  "scene_entry.cpp",
  "BridgeExSwapchain.cppm",
  "BridgeExSwapchain.cpp",
  "scene_main.cpp",
]

[usage]
options = [
  "-Wextra",
  "-Wno-missing-field-initializers",
  "-Wno-gnu-zero-variadic-macro-arguments",
]

[dependencies.owe-core]
workspace = true

[dependencies.owe-scene]
workspace = true

[dependencies.owe-vulkan]
workspace = true

[dependencies.owe-waywallen-producer]
workspace = true

[dependencies.rstd-argparse]
workspace = true

[dependencies.rstd-cppstd]
workspace = true

[dependencies.rstd-log]
workspace = true

[dependencies.rstd-std]
workspace = true

[dependencies.vvk]
workspace = true
